### ISSUE TITLE
PREFIX_IP_PROXY and output not found

### ISSUE THREAD

**Issue by relentless-warrior** [MPTCP-smartphone-thesis/pcap-measurement#3]
When I rant he analyze.py script, I ran into following error:

> PREFIX_IP_PROXY = conf.PREFIX_IP_PROXY
> AttributeError: 'module' object has no attribute 'PREFIX_IP_PROXY'

I then added PREFIX_IP_PROXY with the value of '1.2.3.4' in the config.py file. With this modification the script ran without any error. However, I did not find any output in any of the generated folders. I used the traces from http://crawdad.org/ as input for running the script.

I am wondering if I need to use different values for the attributes in config.py file:

```
PREFIX_IP_PROXY = '1.2.3.4'
# IP address of the proxy/server
IP_PROXY = '1.2.3.4'
# Prefix of IPs belonging to WiFi access points
PREFIX_IP_WIFI = '192.168.'
# The password of SOCKS sessions
PASSWORD = 'My awesome password'
```

**Comment by qdeconinck** [comment]
This repository is no more maintained because it hosts an old version of our project. You can find the current code at [https://github.com/multipath-tcp/mptcp-analysis-scripts](https://github.com/multipath-tcp/mptcp-analysis-scripts).

I think in this version, connections that do not have IP_PROXY as the destination are dropped from the output results (I think 1.2.3.4 is not the IP of the proxy :-) ). This should not be the case with our current code.

If you still experience this issue with our latest version, feel free to create a new issue on that repository.
